on:
  branches:
    - main

permissions:
  contents: read

jobs:
  linter:
    name: Linter code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        id: prepare
        run: npm ci # you can use any custom command, just be sure it includes npm install

      - name: Linter action
        id: linter
        uses: AntonKornus/TypeScript-Linter@1.0.0
        with:
          folder: src # optional
