on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linter:
    name: Linter code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        id: prepare
        run: pnpm install --frozen-lockfile

      - name: Linter action
        id: linter
        uses: AntonKornus/TypeScript-Linter@1.0.0
        with:
          folder: src # optional

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
